name: Angular CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to v3 (latest)

    - name: Set up Node.js
      uses: actions/setup-node@v3  # Updated to v3 (latest)
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build --prod

    - name: Deploy (optional step depending on where you deploy)
      run: |
        # Add your deployment script here (e.g., to Azure, AWS, or other platforms)
